// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RPCTasks.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class RPCTasksHandler : virtual public RPCTasksIf {
 public:
  RPCTasksHandler() {
    // Your initialization goes here
  }

  bool assignMatrix(const Matrix& matrix) {
    // Your implementation goes here
    printf("assignMatrix\n");
  }

  bool calcMatrix(const Operation::type op) {
    // Your implementation goes here
    printf("calcMatrix\n");
  }

  void saveMatrix() {
    // Your implementation goes here
    printf("saveMatrix\n");
  }

  void ping(const std::string& msg) {
    // Your implementation goes here
    printf("ping\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<RPCTasksHandler> handler(new RPCTasksHandler());
  ::std::shared_ptr<TProcessor> processor(new RPCTasksProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

